package gengo_mysql_query

import (
	"bytes"
	"go/format"
	"text/template"

	"github.com/iancoleman/strcase"
)

var (
	tmplQuery = template.Must(template.New("query").Funcs(template.FuncMap{
		"ToSnake": strcase.ToSnake,
	}).Parse(`
	// Code generated by "cdd gen go-ds-mysql". DO NOT EDIT.
	// source: {{.GeneratedFrom}}

	package {{.PackageName}}
	
	import (
		{{ if .NeedImportTime }} "time" {{ end }}
		"gorm.io/gorm"
	)
	
	func ({{.GetName}}) QueryGet(db *gorm.DB, {{ .GetPrimaryKeyAsString "" "" "," true true }}) (*{{.GetName}}, error) {
		result := &{{.GetName}}{}
		err := db.Table("{{.TableName}}").Where("{{ .GetPrimaryKeyAsQueryStmt }}", {{ .GetPrimaryKeyAsString "" "" "," true false }}).First(&result).Error
		return result, err
	}

	func ({{.GetName}}) QueryGetAll(db *gorm.DB, ) ([]*{{.GetName}}, error) {
		result := []*{{.GetName}}{}
		err := db.Table("{{.TableName}}").Find(&result).Error
		return result, err
	}

	func ({{.GetName}}) QueryCreate(db *gorm.DB, in {{.GetName}}) (*{{.GetName}}, error) {
		{{ if or .IsCreatedAt .IsUpdatedAt }} timeNow := time.Now() {{ end }}
		{{ if .IsCreatedAt}} in.CreatedAt = &timeNow {{ end }}
		{{ if .IsUpdatedAt}} in.UpdatedAt = &timeNow {{ end }}

		err := db.Table("{{.TableName}}").Create(&in).Error
		if err != nil {
			return nil, err
		}
		return &in, nil
	}

	func ({{.GetName}}) QueryUpdate(db *gorm.DB, in {{.GetName}}) (*{{.GetName}}, error) {
		{{ if or .IsCreatedAt .IsUpdatedAt }} timeNow := time.Now() {{ end }}
		{{ if .IsCreatedAt}} in.CreatedAt = nil {{ end }}
		{{ if .IsUpdatedAt}} in.UpdatedAt = &timeNow {{ end }}
		err := db.Table("{{.TableName}}").Where("{{ .GetPrimaryKeyAsQueryStmt }}", {{ .GetPrimaryKeyAsString "in." "" "," false false }}).Updates(&in).Error
		if err != nil {
			return nil, err
		}
		return &in, nil
	}

	func ({{.GetName}}) QueryDelete(db *gorm.DB, {{ .GetPrimaryKeyAsString "" "" "," true true }}) error {
		return db.Table("{{.TableName}}").Delete(&{{.GetName}}{}, "{{ .GetPrimaryKeyAsQueryStmt }}", {{ .GetPrimaryKeyAsString "" "" "," true false }}).Error
	}

	`))
)

func applyTemplateQuery(model MysqlModel, packageName string, outputDir string, generatedfrom string) (*generatorResponseFile, error) {

	w := bytes.NewBuffer(nil)
	var tmplData = struct {
		MysqlModel
		PackageName   string
		GeneratedFrom string
	}{
		model,
		packageName,
		generatedfrom,
	}

	if err := tmplQuery.Execute(w, tmplData); err != nil {
		return nil, err
	}

	formatted, err := format.Source([]byte(w.String()))
	if err != nil {
		return nil, err
	}
	return &generatorResponseFile{
		outputPath: outputDir + "/query." + strcase.ToSnake(model.GetName()) + ".gen.go",
		content:    string(formatted),
	}, nil

}
