// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: city.proto
package city

import (
	"net/http"
	"strings"

	"github.com/krisnasw/go-grst/grst"
	grst_errors "github.com/krisnasw/go-grst/grst/errors"
	"google.golang.org/grpc"

	"github.com/mcuadros/go-defaults"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials"
	"gopkg.in/validator.v2"
)

type fullMethods struct {
	City_Get          string
	City_Search       string
	City_FileDownload string
}

var FullMethods = fullMethods{
	City_Get:          "/city.city/Get",
	City_Search:       "/city.city/Search",
	City_FileDownload: "/city.city/FileDownload",
}

var NeedAuthFullMethods = []string{}

type AuthConfig struct {
	NeedAuth bool
	Roles    []string
}

var AuthConfigFullMethods = map[string]AuthConfig{
	"/city.city/Get":          AuthConfig{NeedAuth: false, Roles: []string{"*"}},
	"/city.city/Search":       AuthConfig{NeedAuth: false, Roles: []string{"*"}},
	"/city.city/FileDownload": AuthConfig{NeedAuth: false, Roles: []string{"*"}},
}

var NeedApiKeyFullMethods = []string{}

func ValidateRequest(req interface{}) error {
	defaults.SetDefaults(req)
	if errs := validator.Validate(req); errs != nil {
		validateError := []*grst_errors.ErrorDetail{}
		for field, err := range errs.(validator.ErrorMap) {
			errMessage := strings.Replace(err.Error(), "{field}", field, -1)
			validateError = append(validateError, &grst_errors.ErrorDetail{Code: 999, Field: field, Message: errMessage})
		}
		return grst_errors.New(http.StatusBadRequest, codes.InvalidArgument, 999, "Validation Error", validateError...)
	}

	return nil
}

/*==================== City Section ====================*/

func RegisterCityGrstServer(grpcRestServer *grst.Server, hndl CityServer) {

	forward_City_Get_0 = grpcRestServer.GetForwardResponseMessage()

	forward_City_Search_0 = grpcRestServer.GetForwardResponseMessage()

	forward_City_FileDownload_0 = grpcRestServer.GetForwardResponseMessage()

	RegisterCityServer(grpcRestServer.GetGrpcServer(), hndl)
	grpcRestServer.RegisterRestHandler(RegisterCityHandler)
}

func NewCityGrstClient(serverHost string, creds *credentials.TransportCredentials, dialOpts ...grpc.DialOption) (CityClient, error) {
	opts := []grpc.DialOption{}
	opts = append(opts, grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*20)))
	opts = append(opts, grpc.WithMaxMsgSize(1024*1024*20))
	if creds == nil {
		opts = append(opts, grpc.WithInsecure())
	} else {
		opts = append(opts, grpc.WithTransportCredentials(*creds))
	}
	opts = append(opts, dialOpts...)
	grpcConn, err := grpc.Dial(serverHost, opts...)
	return NewCityClient(grpcConn), err
}
