// Code generated by "cdd gen go-ds-mysql". DO NOT EDIT.
// source: repository/city_mysql/model.go

package city_mysql

import (
	"gorm.io/gorm"
	"time"
)

func (CityModel) QueryGet(db *gorm.DB, id int) (*CityModel, error) {
	result := &CityModel{}
	err := db.Table("tbl_city").Where("id = ?", id).First(&result).Error
	return result, err
}

func (CityModel) QueryGetAll(db *gorm.DB) ([]*CityModel, error) {
	result := []*CityModel{}
	err := db.Table("tbl_city").Find(&result).Error
	return result, err
}

func (CityModel) QueryCreate(db *gorm.DB, in CityModel) (*CityModel, error) {
	timeNow := time.Now()
	in.CreatedAt = &timeNow
	in.UpdatedAt = &timeNow

	err := db.Table("tbl_city").Create(&in).Error
	if err != nil {
		return nil, err
	}
	return &in, nil
}

func (CityModel) QueryUpdate(db *gorm.DB, in CityModel) (*CityModel, error) {
	timeNow := time.Now()
	in.CreatedAt = nil
	in.UpdatedAt = &timeNow
	err := db.Table("tbl_city").Where("id = ?", in.Id).Updates(&in).Error
	if err != nil {
		return nil, err
	}
	return &in, nil
}

func (CityModel) QueryDelete(db *gorm.DB, id int) error {
	return db.Table("tbl_city").Delete(&CityModel{}, "id = ?", id).Error
}
