// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: users.proto

package entity

type UserProfile struct {
	Id           int    `json:"Id"`
	Name         string `json:"name"`
	ProvinceId   int    `json:"province_id"`
	ProvinceName string `json:"province_name"`
}
