// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: users.proto

package entity

type User struct {
	Id         int    `json:"id"`
	Name       string `json:"name"`
	ProvinceId int    `json:"province_id"`
}
