// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: city.proto

package entity

type CityProfile struct {
	Id           int    `json:"id"`
	Name         string `json:"name"`
	ProvinceName string `json:"province_name"`
	ProvinceId   int    `json:"province_id"`
}
