// Code generated by protoc-gen-cdd. DO NOT EDIT.
// source: city.proto

package entity

type City struct {
	Id         int    `json:"id"`
	ProvinceId int    `json:"province_id"`
	Name       string `json:"name"`
}
